/* 
Part 1: ASP.NET Core Request Pipeline (Foundation)
What is the Request Pipeline?
Why is it needed?
How a request flows through ASP.NET Core
Pipeline architecture
Program.cs
WebApplication
Request delegates
Building the pipeline
Complete request lifecycle
Multiple middleware example
Pipeline execution order
Short-circuiting
Real-world request flow
*/


✅🔥 ASP.NET Core Request Pipeline:
The ASP.NET Core Request Pipeline is one of the most important concepts in ASP.NET Core.
Before learning MVC, Routing, Controllers, or Middleware, you must understand how a request travels through the application.


✅🔥 What is the Request Pipeline?
The ASP.NET Core Request Pipeline is a sequence (chain) of software components called middleware that process every incoming HTTP request and outgoing HTTP response.
Every request sent by a client (browser, mobile app, Postman, etc.) passes through this pipeline before reaching your application logic.
Similarly, every response generated by your application travels back through this same pipeline before it is sent to the client.

Browser -> HTTP Request -> Middleware(1,2...n)-> Controller / Endpoint-> HTTP Response -> Middleware(1,2...n) ->Browser


✅🔥 Why is the Request Pipeline Needed?
Without a pipeline, every controller or endpoint would need to perform common tasks repeatedly.

❌Example without a pipeline:
CheckAuthentication();
CheckAuthorization();
LogRequest();
CheckHTTPS();
HandleExceptions();
ExecuteBusinessLogic();
Every controller would contain the same repeated code.

Problems:
   Code duplication
   Difficult maintenance
   Hard debugging
   Poor scalability
   Inconsistent behavior

✅ With the Request Pipeline:
Request
↓
Logging Middleware
↓
Exception Middleware
↓
Authentication Middleware
↓
Authorization Middleware
↓
Routing Middleware
↓
Controller
Now, these common tasks are written once and automatically applied to every request.


------------------------------------------------------------------------------------------------------------

✅🔥 How a Request Flows Through ASP.NET Core
Browser // User enters a URL or clicks a link. The browser creates and sends an HTTP request to the server.
↓
HTTP GET /Home/Index // Example Request:HTTP GET /Home/Index. The browser sends an HTTP GET request asking for the Index action of the Home controller.
↓
Kestrel receives request // Kestrel is ASP.NET Core's built-in web server. It accepts the incoming HTTP request and hands it over to the ASP.NET Core application.
↓
Program.cs builds pipeline // Application Startup: The middleware pipeline defined in Program.cs is responsible for deciding how the request should be processed.
↓
Logging Middleware  // Middleware 1: Logs request information such as URL, HTTP method, execution time, and response status for monitoring and debugging.
↓
Exception Middleware // Middleware 2: Catches unhandled exceptions thrown later in the pipeline and generates an appropriate error response instead of crashing the application.
↓
Authentication Middleware // Middleware 3: Checks whether the request contains valid authentication credentials (Cookie, JWT Token, OAuth, etc.) and identifies the current user.
↓
Authorization Middleware // Middleware 4:  Verifies whether the authenticated user has permission to access the requested resource based on roles or policies.
↓
Routing Middleware  // Middleware 5: Matches the incoming URL (/Home/Index) with the appropriate controller and action using the application's routing configuration.
↓
MVC Controller // ASP.NET Core creates the appropriate controller object using Dependency Injection and prepares to execute the requested action.
↓
HomeController.Index() // The Index() action executes the application's business logic, retrieves data if necessary, and returns an ActionResult (usually a View).
↓
View // Razor View Engine: The Razor View Engine renders the corresponding .cshtml view by combining HTML with the data (Model) provided by the controller.
↓
HTML Response // The rendered HTML is packaged into an HTTP response and sent back through the middleware pipeline to Kestrel.
↓
Browser // Client: The browser receives the HTML response, parses it, loads CSS/JavaScript/images if needed, and displays the final web page to the user.


==================================================================================================================

✅🔥Program.cs
In ASP.NET Core, Program.cs is the application's entry point.
It is responsible for:
   Creating the application
   Starting the web server
   Registering services
   Building the request pipeline
Example:
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllersWithViews();
var app = builder.Build();

// Building the Pipeline
app.UseHttpsRedirection(); 
app.UseStaticFiles(); 
app.UseRouting(); 
app.UseAuthentication();
app.UseAuthorization();
app.MapControllerRoute( // Maps incoming URLs to MVC controllers using the default route.
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");
app.Run();
Key parts:
    builder.Services → Registers services used by the app (Dependency Injection).
    builder.Build() → Creates the WebApplication.
    app.Use...() → Adds middleware to the request pipeline.
    app.Map...() → Maps endpoints (such as MVC controllers).
    app.Run() → Starts listening for incoming HTTP requests.


=====================      Detailed Explanation        ==============================================================
// Creates a WebApplicationBuilder object.
// It initializes the ASP.NET Core application, loads configuration files
// (appsettings.json, environment variables, command-line arguments),
// sets up Dependency Injection (DI), Logging, and Configuration services.
var builder = WebApplication.CreateBuilder(args);

// ---------------------------
// Register Services
// ---------------------------

// Registers MVC services into the Dependency Injection (DI) container.
// This adds support for:
// • Controllers
// • Razor Views (.cshtml)
// • Model Binding
// • Model Validation
// • Action Filters
// • Routing
// • View Engine
// Without this line, the application cannot use the MVC pattern.
builder.Services.AddControllersWithViews();

// ---------------------------
// Build the Application
// ---------------------------

// Creates the WebApplication object.
// At this point, all registered services are finalized,
// and the application instance is ready to configure the HTTP request pipeline.
var app = builder.Build();

// ---------------------------
// Configure Middleware Pipeline
// ---------------------------

// Redirects all HTTP requests to HTTPS.
// Example:
// http://localhost:5000/Home/Index
//          ↓
// https://localhost:5001/Home/Index
// This improves application security by encrypting communication.
app.UseHttpsRedirection();

// Enables serving static files from the "wwwroot" folder.
// Static files include:
// • CSS
// • JavaScript
// • Images
// • Fonts
// • PDF files
// Requests for these files are served directly without reaching MVC.
app.UseStaticFiles();

// Adds the Routing Middleware.
// It analyzes the incoming URL and determines which endpoint
// (Controller + Action) should handle the request.
// Example:
// /Home/About
// Controller = Home
// Action = About
app.UseRouting();

// Adds Authentication Middleware.
// It checks whether the incoming request contains valid
// authentication credentials such as:
// • Cookie Authentication
// • JWT Token
// • OAuth
// If authentication succeeds, HttpContext.User is populated.
app.UseAuthentication();

// Adds Authorization Middleware.
// After the user is authenticated,
// this middleware checks whether the user has permission
// to access the requested resource.
// It evaluates:
// • Roles
// • Policies
// • Claims
// If authorization fails, the request is rejected.
app.UseAuthorization();

// Maps incoming URLs to MVC controllers using the default route.
//
// Route Template:
// {controller=Home}/{action=Index}/{id?}
//
// Meaning:
// controller -> Defaults to Home
// action     -> Defaults to Index
// id         -> Optional parameter
//
// Examples:
//
// URL: /
// Controller = Home
// Action = Index
//
// URL: /Home/About
// Controller = Home
// Action = About
//
// URL: /Product/Details/10
// Controller = Product
// Action = Details
// id = 10
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

// Starts the Kestrel web server.
// After this line executes:
// • The application begins listening for HTTP requests.
// • The configured middleware pipeline starts processing requests.
// • This is a blocking call—the application keeps running
//   until it is stopped (for example, Ctrl+C or application shutdown).
app.Run();



























